import {
  SiDotnet,
  SiReact,
  SiTypescript,
  SiJavascript,
  SiGit,
  SiSelenium,
  SiDocker,
  SiJira,
  SiNotion,
  SiConfluence,
  SiPostman,
  SiInsomnia,
  SiGitlab,
  SiOpenai,
  SiGithubcopilot,
} from 'react-icons/si'
import {
  VscVscode,
  VscAzureDevops,
} from 'react-icons/vsc'
import {
  TbBrandAzure,
  TbTestPipe,
  TbManualGearbox,
  TbBrandSpeedtest,
  TbRepeat,
  TbUsers,
  TbDatabase,
  TbBrowser,
} from 'react-icons/tb'
import {
  BsRobot,
} from 'react-icons/bs'
import type { IconType } from 'react-icons'

export const skillIcons: Record<string, IconType> = {
  '.NET': SiDotnet,
  'C#': SiDotnet,
  'ASP.NET': SiDotnet,
  'React': SiReact,
  'TypeScript': SiTypescript,
  'JavaScript': SiJavascript,
  'SQL': TbDatabase,
  'Git': SiGit,
  'Selenium': SiSelenium,
  'Playwright': TbBrowser,
  'xUnit': TbTestPipe,
  'Locust': TbBrandSpeedtest,
  'Tests manuels': TbManualGearbox,
  'GitLab CI': SiGitlab,
  'Docker': SiDocker,
  'Azure DevOps': VscAzureDevops,
  'Azure OpenAI': SiOpenai,
  'Azure AI Foundry': TbBrandAzure,
  'RAG': BsRobot,
  'JIRA': SiJira,
  'Agile': TbRepeat,
  'SCRUM': TbUsers,
  'VS Code': VscVscode,
  'Rider': SiDotnet,
  'Postman': SiPostman,
  'Insomnia': SiInsomnia,
  'Notion': SiNotion,
  'Confluence': SiConfluence,
  'GitHub Copilot': SiGithubcopilot,
  'Claude': BsRobot,
  'ChatGPT': SiOpenai,
  'SQL Server': TbDatabase,
}
